workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      vars:
        NODE_VERSION: 18.16.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Next.js
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - neerajverma94244@gmail.com
