workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      groups:
        - next-env
      vars:
        NODE_VERSION: 18.16.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Create Android assets folder
        script: |
          mkdir -p android/app/src/main/assets
      - name: Update Capacitor
        script: |
          npx cap update android
      - name: Make gradlew executable
        script: |
          cd android
          chmod +x gradlew
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - neerajverma94244@gmail.com
